---
- name: deploy GRAFANA as a Docker container to the target machine
  hosts: "{{ target }}"
  become: true

  pre_tasks:
    - debug: msg="{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    - file:
        path: /var/log/ansible.log
        state: touch
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: "u=rw,g=rw,o=rw"
      become: true

  roles:
    - docker-grafana

