# DEFAULT VM CONFIG
vm_user: centos
nbofvms: 1
image: ce7-cldimg
flavor: m1.sp
os_security_groups: "{{ plat }}-secgrp"
fip: provider
availability_zone: nova
region_name: RegionOne
key_name: son-install

# DEMO-NET
##int_net_id: "ea7d9c50-5b1e-4968-804d-a6ec11c318c5" # sonata.dem-net
#ext_net_id: "53d43a3e-8c86-48e6-b1cb-f1f2c48833de" # provider

# QUAL-NET
#int_net_id: "fdca8a94-e34f-42b3-aba1-75a169985ddd" # sonata.qual-net
ext_net_id: "12bf4db8-0131-4322-bd22-0b1ad8333748" # provider
