---

- name: MANO SDN (Docker container)
  docker_container:
    name: sdn
    image: "sonatanfv/sdn"
    env:
      url_gk_api: "http://son-gtkapi:5000/api/v2/"
      url_nsr_repository: "http://son-catalogue-repos:4011/records/nsr/"
      url_vnfr_repository: "http://son-catalogue-repos:4011/records/vnfr/"
      url_monitoring_server: http://son-monitor-manager:8000/api/v1/
      broker_host: amqp://guest:guest@son-broker:5672/%2F
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - sdn
        links:
          - son-broker
    restart_policy: "always"
    state: started

