---
- debug: msg="##### SP GTK-KEYCLOAK DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

- name: run the SP Keycloak service
  docker_container:
    name: "son-keycloak"
    image: "tdierich/son-keycloak"
    env:
      #Default: KEYCLOAK_USER: admin KEYCLOAK_PASSWORD: admin
      KEYCLOAK_USER: "{{ gtk_keycloak_user }}" 
      KEYCLOAK_PASSWORD: "{{ gtk_keycloak_pass }}"
      SONATA_USER: "pishahang"
      SONATA_PASSWORD: "1234"
      SONATA_EMAIL: "pishahang@gmail.com"
    state: started
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-keycloak
    published_ports:
      - "5601:5601"
    restart_policy: "always"
