databases:
  mongo: mongodb://mongo/gatekeeper
  redis: redis://redis:6379/gatekeeper

broker:
  host: amqp://guest:guest@broker:5672/%2F
  exchange: son-kernel

initialUserData:
  username: pishahang
  password: "1234"
  isAdmin: true

jwt:
  accessTokenLifetime: 900 # 15 min
  refreshTokenLifetime: 604800 # 7 days

connexion:
  validateResponses: false
  options:
    swagger_ui_config:
      showExtensions: true
