databases:
  mongo: mongodb://mongo/gatekeeper
  redis: redis://redis:6379/gatekeeper

broker:
  host: amqp://guest:guest@broker:5672/%2F
  exchange: son-kernel

internalApis:
  pluginmanager: http://mano-pluginmanager:8001/api/plugins

initialUserData:
  username: pishahang
  password: "1234"
  isAdmin: true
  fullName: "Admin"
  email: "pishahang@example.org"

jwt:
  accessTokenLifetime: 900 # 15 min
  refreshTokenLifetime: 604800 # 7 days

connexion:
  validateResponses: false
  options:
    swagger_ui_config:
      showExtensions: true
